parameters:
    uneak.flatskin.type.gender.class: Uneak\FlatSkinBundle\Form\GenderType
    uneak.flatskin.type.date_picker.class: Uneak\FlatSkinBundle\Form\DatePickerType
    uneak.flatskin.type.location_picker.class: Uneak\FlatSkinBundle\Form\LocationPickerType

services:

    uneak.flatskin.type.gender:
        class: %uneak.flatskin.type.gender.class%
        tags:
            - { name: form.type, alias: gender }

    uneak.flatskin.type.date_picker:
        class: %uneak.flatskin.type.date_picker.class%
        tags:
            - { name: form.type, alias: date_picker }

    uneak.flatskin.type.location_picker:
        class: %uneak.flatskin.type.location_picker.class%
        tags:
            - { name: form.type, alias: location_picker }