parameters:
    uneak.flatskin.type.gender.class: Uneak\FlatSkinBundle\Form\GenderType
    uneak.flatskin.type.date_picker.class: Uneak\FlatSkinBundle\Form\DatePickerType
    uneak.flatskin.type.location_picker.class: Uneak\FlatSkinBundle\Form\LocationPickerType
    uneak.flatskin.type.file_picker.class: Uneak\FlatSkinBundle\Form\FilePickerType
    uneak.flatskin.type.choice.select2.class: Uneak\FlatSkinBundle\Form\ChoiceSelect2Type
    uneak.flatskin.type.entity.select2.class: Uneak\FlatSkinBundle\Form\EntitySelect2Type
    uneak.flatskin.type.ckeditor.class: Uneak\FlatSkinBundle\Form\CKEditorType
    uneak.flatskin.type.route.class: Uneak\FlatSkinBundle\Form\RouteType
    uneak.flatskin.type.routes.class: Uneak\FlatSkinBundle\Form\RoutesType

services:

    uneak.flatskin.type.gender:
        class: %uneak.flatskin.type.gender.class%
        tags:
            - { name: form.type, alias: gender }

    uneak.flatskin.type.date_picker:
        class: %uneak.flatskin.type.date_picker.class%
        tags:
            - { name: form.type, alias: date_picker }

    uneak.flatskin.type.location_picker:
        class: %uneak.flatskin.type.location_picker.class%
        tags:
            - { name: form.type, alias: location_picker }

    uneak.flatskin.type.choice.select2:
        class: %uneak.flatskin.type.choice.select2.class%
        tags:
            - { name: form.type, alias: choice_select2 }

    uneak.flatskin.type.entity.select2:
        class: %uneak.flatskin.type.entity.select2.class%
        tags:
            - { name: form.type, alias: entity_select2 }

    uneak.flatskin.type.ckeditor:
        class: %uneak.flatskin.type.ckeditor.class%
        tags:
            - { name: form.type, alias: ckeditor }

    uneak.flatskin.type.file_picker:
        class: %uneak.flatskin.type.file_picker.class%
        tags:
            - { name: form.type, alias: file_picker }


    uneak.flatskin.type.routes:
        class: %uneak.flatskin.type.routes.class%
        arguments:
            - %routes%
        tags:
            - { name: form.type, alias: routes }

    uneak.flatskin.type.route:
        class: %uneak.flatskin.type.route.class%
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: route }